### ISSUE TITLE
SelectedPageIndex isn't be updated after user change the page

### ISSUE THREAD

**Issue by jingliancui** [marcelwgn/PagerControlPolyfill#3]
1. bind the SelectedPageIndex to a property in viewmodel with mode=twoway
2. binding property set to 5
3. set the number of page to 20
4. start to debug
5. click the next page button

expect:
binding property should become 6

actually:
binding property keep equals to 5

**Comment by marcelwgn** [comment]
Binding might not work if not all entities in the chain support INotifyPropertyChanged. So if you add the ViewModel as a property of a class that does not support that interface, binding won't work since the first step in the chain doesn't support it. The test app of this repo has been updated to also showcase DataBinding and it seems to work correctly. Could you check if implementing that correctly solves the issue for you?

**Comment by jingliancui** [comment]
thank you so much , I think I should do some code change on my code, it should be my bad. thank you.
